import { StyleSheet } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { BRAND } from '@/constants/colors';
type Palette = ReturnType<typeof useColors>;

export function createStyles(colors: Palette, roundColor: string = BRAND.yellow) {
  return StyleSheet.create({
    homeHero: { alignItems: 'stretch' },
    claim: { textAlign: 'center', fontFamily: 'Inter_900Black', fontSize: 21, letterSpacing: 1, color: BRAND.white },
    teamCards: { gap: 14 },
    teamCard: { padding: 16, borderRadius: 26, backgroundColor: colors.card, borderTopWidth: 5 },
    teamAvatar: { width: 54, height: 54, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    teamAvatarText: { fontSize: 28 },
    deckTileContent: { alignItems: 'center' },
    roundHero: { alignItems: 'center', paddingTop: 26, paddingBottom: 12, gap: 20 },
    roundHeroIcon: { width: 116, height: 116, borderRadius: 36, backgroundColor: roundColor, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-6deg' }] },
    roundHeroTitle: { fontFamily: 'Inter_900Black', fontSize: 38, lineHeight: 44, color: roundColor, textAlign: 'center', textTransform: 'uppercase' },
    durationPill: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 22, padding: 12, borderRadius: 18, backgroundColor: roundColor },
    durationText: { flexShrink: 1, fontFamily: 'Inter_700Bold', fontSize: 13, color: BRAND.navy },
    readyScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 24, paddingBottom: 24 },
    handoffCard: { alignItems: 'center', paddingHorizontal: 16, paddingBottom: 24, borderRadius: 28, backgroundColor: colors.card },
    handoffIcon: { fontSize: 40, marginTop: 18 },
    handoffName: { fontFamily: 'Inter_900Black', fontSize: 36, lineHeight: 42, color: roundColor, textAlign: 'center', marginTop: 12 },
    playTeamHeader: { flex: 1, minWidth: 0 },
    reviewHeading: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 14 },
    reviewPoints: { fontFamily: 'Inter_900Black', fontSize: 44, color: BRAND.navy },
    repeatMessage: { alignItems: 'center', marginBottom: 24 },
    repeatTitle: { fontFamily: 'Inter_900Black', fontSize: 26, textAlign: 'center', color: BRAND.white },
    nextRoundCard: { borderRadius: 24, padding: 22, marginBottom: 20, gap: 8, transform: [{ rotate: '-2deg' }] },
    nextRoundLabel: { fontFamily: 'Inter_700Bold', fontSize: 12, textTransform: 'uppercase', color: BRAND.navy },
    nextRoundTitle: { fontFamily: 'Inter_900Black', fontSize: 28, textTransform: 'uppercase', color: BRAND.navy },
    checklist: { borderRadius: 22, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, overflow: 'hidden', marginTop: 20, marginBottom: 16 },
    checkRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 68, padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border },
    checkRowCorrect: { backgroundColor: '#123D3B' },
    checkBox: { width: 27, height: 27, borderRadius: 8, borderWidth: 2, borderColor: colors.mutedForeground, alignItems: 'center', justifyContent: 'center' },
    checkBoxCorrect: { backgroundColor: BRAND.mint, borderColor: BRAND.mint },
    checkWord: { flex: 1, fontFamily: 'Inter_700Bold', fontSize: 16, lineHeight: 23, color: colors.foreground },
    checkStatus: { fontFamily: 'Inter_600SemiBold', fontSize: 12, color: colors.mutedForeground, paddingVertical: 5, paddingHorizontal: 8, borderRadius: 8, backgroundColor: colors.secondary },
    checkStatusCorrect: { color: BRAND.navy, backgroundColor: BRAND.mint },
    reviewSummary: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 12, marginTop: 24, padding: 22, borderRadius: 24, backgroundColor: BRAND.mint },
    reviewSummaryText: { flexShrink: 1, fontFamily: 'Inter_700Bold', fontSize: 16, color: BRAND.navy },
    reviewSummaryNote: { fontFamily: 'Inter_500Medium', fontSize: 13, color: BRAND.navy },
    reviewFooter: { width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 24, paddingVertical: 16, backgroundColor: colors.background },
    languageSelectorRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginTop: 8 },
    languageSelectorLabel: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.2, color: colors.mutedForeground },
    languageSelectorPillGroup: { flexDirection: 'row', gap: 6, alignItems: 'center' },
    languageSelectorPill: { minWidth: 38, height: 34, paddingHorizontal: 11, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
    languageSelectorPillActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    languageSelectorText: { fontFamily: 'Inter_700Bold', fontSize: 11, color: colors.foreground },
    languageSelectorTextActive: { color: colors.primaryForeground },
    tableRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 17, borderBottomWidth: 1, borderBottomColor: colors.border },
    tableHeader: { backgroundColor: colors.secondary },
    tableLabel: { flex: 1.4, fontFamily: 'Inter_600SemiBold', fontSize: 14, color: colors.foreground },
    tableNumber: { flex: 1, textAlign: 'center', fontFamily: 'Inter_700Bold', fontSize: 20, color: colors.foreground },
    tableHeading: { fontSize: 12, color: colors.mutedForeground },
    tableTotal: { backgroundColor: colors.secondary, borderBottomWidth: 0 },
    tableTotalNumber: { color: colors.primary, fontSize: 25 },
    safe: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    homeScroll: { flexGrow: 1, width: '100%', maxWidth: 520, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 12, paddingBottom: 30 },
    pageScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 24, paddingBottom: 30 },
    heroOverline: { marginTop: 26, textAlign: 'center', fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 2, color: colors.mutedForeground },
    statsRow: { flexDirection: 'row', gap: 8, marginBottom: 22, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 6 },
    stat: { flex: 1, alignItems: 'center', paddingVertical: 12 },
    statValue: { fontFamily: 'Inter_900Black', fontSize: 17, textAlign: 'center', color: colors.foreground },
    statLabel: { marginTop: 4, fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.mutedForeground },
    primaryButton: { minHeight: 62, borderRadius: 22, paddingHorizontal: 22, paddingVertical: 16, flexDirection: 'row', gap: 12, alignItems: 'center', justifyContent: 'space-between', backgroundColor: roundColor, borderBottomWidth: 4, borderBottomColor: '#00000025' },
    primaryButtonText: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 16, color: colors.primaryForeground },
    secondaryButton: { minHeight: 64, borderRadius: 22, marginTop: 12, padding: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: colors.border },
    secondaryButtonText: { fontFamily: 'Inter_600SemiBold', fontSize: 15, color: colors.foreground },
    secondaryButtonNote: { marginTop: 4, fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.mutedForeground },
    footnote: { marginTop: 18, textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, color: colors.mutedForeground },
    pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
    screenHeader: { height: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    screenHeaderTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 15, color: colors.foreground },
    iconButton: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card },
    iconButtonPlaceholder: { width: 38, height: 38 },
    pageEyebrow: { marginTop: 22, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.5, color: roundColor },
    pageTitle: { marginTop: 10, fontFamily: 'Inter_900Black', fontSize: 34, lineHeight: 39, letterSpacing: -1.2, color: colors.foreground },
    pageSubtitle: { marginTop: 11, fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 24, color: colors.mutedForeground },
    formBlock: { marginTop: 24 },
    fieldLabel: { marginBottom: 10, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.1, color: colors.mutedForeground },
    teamInputRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 12 },
    teamInput: { flex: 1, minWidth: 0, fontFamily: 'Inter_700Bold', fontSize: 20, color: colors.foreground, paddingVertical: 12 },
    teamIconPicker: { flexDirection: 'row', gap: 4, flexWrap: 'wrap', marginTop: 14 },
    teamIconOption: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.secondary, borderWidth: 2, borderColor: colors.secondary },
    teamIconOptionActive: { backgroundColor: colors.background, borderColor: colors.primary },
    teamIconOptionText: { fontSize: 21 },
    placeholder: { color: colors.mutedForeground },
    cardCountList: { flexDirection: 'row', gap: 10 },
    cardCountOption: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 18, paddingHorizontal: 6, borderRadius: 22, backgroundColor: colors.card, borderWidth: 2, borderColor: colors.border },
    cardCountOptionSelected: { borderColor: colors.primary, backgroundColor: colors.secondary },
    cardCountTitle: { textAlign: 'center', fontFamily: 'Inter_900Black', fontSize: 34, color: colors.foreground },
    cardCountTitleSelected: { color: colors.primary },
    cardCountNote: { marginTop: 5, textAlign: 'center', fontFamily: 'Inter_500Medium', fontSize: 11, color: colors.mutedForeground },
    infoBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginTop: 22, marginBottom: 22, padding: 17, borderRadius: 19, backgroundColor: colors.secondary, borderWidth: 1, borderColor: colors.border },
    infoText: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, color: colors.secondaryForeground },
    instructionCard: { marginTop: 12, padding: 24, borderRadius: 28, backgroundColor: BRAND.white },
    instructionTitle: { fontFamily: 'Inter_900Black', fontSize: 23, color: BRAND.navy, textAlign: 'center' },
    instructionBody: { marginTop: 12, textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 23, color: '#354D60' },
    scoreStrip: { flexDirection: 'row', alignItems: 'center', marginTop: 20, marginBottom: 24, padding: 18, borderRadius: 24, backgroundColor: colors.card },
    scoreTeam: { flex: 1 },
    scoreTeamRight: { alignItems: 'flex-end' },
    scoreTeamNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    scoreTeamNameRowRight: { flexDirection: 'row', alignItems: 'center', gap: 6, justifyContent: 'flex-end' },
    scoreTeamIcon: { fontSize: 16 },
    scoreTeamName: { flexShrink: 1, fontFamily: 'Inter_600SemiBold', fontSize: 12, color: colors.mutedForeground },
    scoreNumber: { marginTop: 6, fontFamily: 'Inter_900Black', fontSize: 32, color: colors.foreground },
    scoreDivider: { marginHorizontal: 16, fontFamily: 'Inter_700Bold', fontSize: 20, color: colors.mutedForeground },
    gameScreen: { flexGrow: 1, width: '100%', maxWidth: 600, alignSelf: 'center', paddingHorizontal: 20, paddingBottom: 16 },
    playHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingTop: 14 },
    playHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 9 },
    playRound: { fontFamily: 'Inter_700Bold', fontSize: 10, lineHeight: 16, letterSpacing: 0.5, color: roundColor },
    activeTeamNameRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 5 },
    activeTeamIcon: { fontSize: 22 },
    activeTeam: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 21, color: colors.foreground },
    timer: { width: 78, height: 78, borderRadius: 39, alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: roundColor, backgroundColor: colors.background },
    timerDanger: { backgroundColor: BRAND.coral, borderColor: BRAND.white },
    timerNumber: { fontFamily: 'Inter_900Black', fontSize: 29, lineHeight: 32, color: colors.foreground },
    timerLabel: { fontFamily: 'Inter_700Bold', fontSize: 10, color: colors.foreground },
    progressTrack: { height: 7, marginTop: 18, overflow: 'hidden', borderRadius: 4, backgroundColor: colors.secondary },
    progressFill: { height: 7, borderRadius: 4, backgroundColor: roundColor },
    playCenter: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 20 },
    cardOverline: { marginBottom: 12, fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.2, color: colors.mutedForeground },
    wordCard: { width: '100%', minHeight: 280, alignItems: 'center', justifyContent: 'space-between', gap: 28, padding: 24, borderRadius: 30, backgroundColor: BRAND.white, borderBottomWidth: 8, borderBottomColor: roundColor },
    cardTopRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center', gap: 8 },
    cardCategory: { fontFamily: 'Inter_700Bold', fontSize: 11, textAlign: 'center', color: '#40586B' },
    cardDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.border },
    wordText: { textAlign: 'center', fontFamily: 'Inter_900Black', fontSize: 38, lineHeight: 44, letterSpacing: -1.3, color: BRAND.navy },
    cardSubcategory: { fontFamily: 'Inter_500Medium', fontSize: 13, textAlign: 'center', color: '#40586B' },
    remainingText: { marginTop: 14, fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.mutedForeground },
    playActions: { flexDirection: 'row', gap: 12 },
    passButton: { flex: 1, minHeight: 66, padding: 12, borderRadius: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
    passButtonText: { flexShrink: 1, fontFamily: 'Inter_700Bold', fontSize: 15, color: colors.foreground },
    correctButton: { flex: 1.5, minHeight: 66, padding: 12, borderRadius: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: roundColor, borderBottomWidth: 4, borderBottomColor: '#00000025' },
    correctButtonText: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 16, color: BRAND.navy },
    scoreBoard: { flexDirection: 'row', gap: 12, marginTop: 26, marginBottom: 8 },
    scoreBoardRow: { flex: 1, minWidth: 0, alignItems: 'center', padding: 18, borderRadius: 24, backgroundColor: colors.card, gap: 8 },
    scoreBoardRowLast: { borderBottomWidth: 0 },
    teamScoreBadge: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center' },
    teamScoreBadgeWarm: { backgroundColor: colors.primary },
    teamScoreBadgeGold: { backgroundColor: colors.accent },
    teamScoreInitial: { fontFamily: 'Inter_700Bold', fontSize: 18, color: colors.primaryForeground },
    scoreBoardName: { textAlign: 'center', fontFamily: 'Inter_700Bold', fontSize: 14, color: colors.foreground },
    scoreBoardPoints: { fontFamily: 'Inter_900Black', fontSize: 46, color: colors.foreground },
    pointsLabel: { fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.mutedForeground },
    finalHero: { alignItems: 'center' },
    finalTitle: { marginTop: 13, fontFamily: 'Inter_900Black', fontSize: 36, lineHeight: 42, letterSpacing: -1.2, textAlign: 'center', color: BRAND.yellow },
  });
}
