import { StyleSheet } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { BRAND } from '@/constants/colors';
type Palette = ReturnType<typeof useColors>;

export function createStyles(colors: Palette, roundColor: string = BRAND.orange) {
  return StyleSheet.create({
    background: { flex: 1, width: '100%', height: '100%', backgroundColor: BRAND.navy },
    homeHero: { alignItems: 'stretch' },
    homeBrandImage: { width: '100%', height: 188, marginTop: 4 },
    homeRoundCardsImage: { width: '100%', height: 188, marginTop: -8, marginBottom: -4 },
    referenceArt: { width: '100%', height: 180, alignSelf: 'center' },
    claim: { textAlign: 'center', fontFamily: 'Inter_900Black', fontSize: 18, letterSpacing: 2.2, color: BRAND.white },
    homeMottoList: { marginTop: 10, marginBottom: 10, padding: 14, borderRadius: 22, backgroundColor: '#FFFFFF10', borderWidth: 1, borderColor: '#FFFFFF20' },
    homeMottoRow: { minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 10 },
    homeMottoIcon: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
    homeMottoText: { flex: 1, fontFamily: 'Inter_700Bold', fontSize: 14, lineHeight: 19, color: BRAND.white },
    teamCards: { flexDirection: 'row', gap: 10 },
    teamCard: { flex: 1, minWidth: 0, padding: 11, borderRadius: 16, backgroundColor: colors.card, borderTopWidth: 4 },
    teamAvatar: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
    teamAvatarText: { fontSize: 23 },
    deckTileContent: { alignItems: 'center' },
    roundInstructionLabel: { marginTop: 12, textAlign: 'center', fontFamily: 'Inter_900Black', fontSize: 16, color: BRAND.navy },
    round1InstructionsArt: { width: '100%', height: 220, marginTop: 8, alignSelf: 'center' },
    instructionsRoundOneScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 16, paddingTop: 5, paddingBottom: 22 },
    instructionsLogo: { width: 190, height: 78, alignSelf: 'center', marginBottom: 4 },
    instructionsRoundOneArt: { width: '100%', height: 460, maxHeight: '64%', alignSelf: 'center' },
    instructionsStartButton: { width: '100%', minHeight: 70, marginTop: 14, backgroundColor: BRAND.orange, borderBottomColor: '#B85E16' },
    instructionsStartButtonText: { flexShrink: 1, paddingHorizontal: 22, fontFamily: 'Inter_900Black', fontSize: 20, textAlign: 'center', textTransform: 'uppercase', color: BRAND.navy },
    roundHero: { alignItems: 'center', paddingTop: 16, paddingBottom: 10, gap: 12 },
    roundHeroIcon: { width: 104, height: 104, borderRadius: 52, backgroundColor: BRAND.white, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-6deg' }] },
    roundHeroTitle: { fontFamily: 'Inter_900Black', fontSize: 37, lineHeight: 42, color: BRAND.navy, textAlign: 'center', textTransform: 'uppercase' },
    durationPill: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 18, padding: 11, borderRadius: 18, backgroundColor: roundColor },
    durationText: { flexShrink: 1, fontFamily: 'Inter_700Bold', fontSize: 13, color: BRAND.navy },
    readyScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: 8, paddingBottom: 20 },
    readyHeader: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    readyLogo: { width: 150, height: 64 },
    readyScoreboard: { minWidth: 150, height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 11, borderRadius: 26, borderWidth: 3, borderColor: '#17628F', backgroundColor: '#041A2E99' },
    readyScoreTeam: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
    readyScoreIcon: { fontSize: 24, lineHeight: 28 },
    readyScoreValue: { fontFamily: 'Inter_900Black', fontSize: 22, color: BRAND.white },
    readyScoreDivider: { width: 2, height: 32, marginHorizontal: 8, backgroundColor: '#17628F' },
    readyMain: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 10 },
    readyHeadline: { width: '100%', maxWidth: 480, fontFamily: 'Inter_900Black', fontSize: 36, lineHeight: 40, letterSpacing: -1.7, textAlign: 'center', color: BRAND.white },
    readyHeadlineAccent: { color: BRAND.orange },
    readyPassArt: { width: '100%', height: 150, marginTop: 4, marginBottom: 0 },
    readyPhoneArt: { width: '82%', height: 105, marginTop: -4, marginBottom: 0 },
    readyTeamLabel: { fontFamily: 'Inter_900Black', fontSize: 17, letterSpacing: 1.5, color: BRAND.orange },
    readyTeamName: { marginTop: 2, fontFamily: 'Inter_900Black', fontSize: 32, lineHeight: 38, textAlign: 'center', color: BRAND.white, textShadowColor: '#00101F', textShadowOffset: { width: 0, height: 4 }, textShadowRadius: 2 },
    readyPrivacyRow: { marginTop: 13, alignItems: 'center', gap: 5 },
    readyPrivacyText: { fontFamily: 'Inter_600SemiBold', fontSize: 14, lineHeight: 18, textAlign: 'center', color: BRAND.white },
    readyButton: { minHeight: 60, marginTop: 14, borderRadius: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: BRAND.orange, borderBottomWidth: 5, borderBottomColor: '#B85E16' },
    readyButtonText: { fontFamily: 'Inter_900Black', fontSize: 22, letterSpacing: 0.4, textAlign: 'center', textTransform: 'uppercase', color: BRAND.navy },
    handoffCard: { alignItems: 'center', paddingHorizontal: 12, paddingBottom: 20 },
    handoffHeadline: { fontFamily: 'Inter_900Black', fontSize: 38, lineHeight: 42, color: BRAND.white, textAlign: 'center', textTransform: 'uppercase' },
    handoffTeamLabel: { marginTop: 20, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.4, color: BRAND.white, textTransform: 'uppercase' },
    handoffName: { minWidth: 180, marginTop: 8, paddingHorizontal: 25, paddingVertical: 12, borderRadius: 28, overflow: 'hidden', fontFamily: 'Inter_900Black', fontSize: 25, lineHeight: 29, color: BRAND.navy, textAlign: 'center', backgroundColor: BRAND.orange },
    playTeamHeader: { flex: 1, minWidth: 0 },
    playLogo: { alignItems: 'center', height: 34 },
    playBrandLogo: { width: 150, height: 58, alignSelf: 'center', marginTop: 2, marginBottom: -2 },
    reviewHeading: { alignItems: 'center', marginTop: 18 },
    reviewTimeTitle: { fontFamily: 'Inter_900Black', fontSize: 39, lineHeight: 44, color: BRAND.white, textTransform: 'uppercase' },
    timeUpArt: { width: '100%', height: 90, marginTop: 8 },
    reviewPoints: { fontFamily: 'Inter_900Black', fontSize: 44, color: BRAND.navy },
    repeatMessage: { alignItems: 'center', marginBottom: 24 },
    repeatTitle: { fontFamily: 'Inter_900Black', fontSize: 26, textAlign: 'center', color: BRAND.white },
    nextRoundCard: { borderRadius: 24, padding: 22, marginBottom: 20, gap: 8, transform: [{ rotate: '-2deg' }] },
    nextRoundLabel: { fontFamily: 'Inter_700Bold', fontSize: 12, textTransform: 'uppercase', color: BRAND.navy },
    nextRoundTitle: { fontFamily: 'Inter_900Black', fontSize: 28, textTransform: 'uppercase', color: BRAND.navy },
    roundBreakScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 16, paddingTop: 8, paddingBottom: 20 },
    roundBreakHeroWrap: { width: '100%', maxWidth: 520, alignSelf: 'center', marginBottom: 4 },
    roundBreakHeroArt: { width: '100%', height: 210, alignSelf: 'center' },
    roundBreakLogo: { width: 195, height: 82, alignSelf: 'center' },
    roundBreakDynamicTitle: { marginTop: 4, fontFamily: 'Inter_900Black', fontSize: 42, lineHeight: 45, textAlign: 'center', color: BRAND.white },
    roundBreakScores: { flexDirection: 'row', gap: 10, marginTop: 2, marginBottom: 8 },
    roundBreakScoreCard: { flex: 1, minWidth: 0, alignItems: 'center', paddingVertical: 12, paddingHorizontal: 6, borderRadius: 19, borderBottomWidth: 4, borderBottomColor: '#001A2F40' },
    roundBreakScoreName: { fontFamily: 'Inter_900Black', fontSize: 12, textAlign: 'center', color: BRAND.navy },
    roundBreakScoreValue: { marginTop: 2, fontFamily: 'Inter_900Black', fontSize: 32, color: BRAND.navy },
    roundBreakRepeatArt: { width: '100%', height: 120, maxHeight: 126, alignSelf: 'center', marginBottom: 1 },
    roundBreakNextArtWrap: { width: '100%', maxWidth: 520, alignSelf: 'center', justifyContent: 'center', marginVertical: 2 },
    roundBreakNextArt: { width: '100%', height: 145, maxHeight: 170, alignSelf: 'center' },
    roundBreakNextArtRound3: { width: '100%', height: 245, alignSelf: 'center', marginTop: -12, marginBottom: -12 },
    roundBreakButton: { minHeight: 60, borderRadius: 30, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderBottomWidth: 5, borderBottomColor: '#001A2F42' },
    roundBreakButtonText: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 16, textAlign: 'center', textTransform: 'uppercase', color: BRAND.navy },
    globalHomeButton: { position: 'absolute', zIndex: 10, top: 14, right: 16, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF18', borderWidth: 1, borderColor: '#FFFFFF40' },
    backFloating: { position: 'absolute', zIndex: 4, left: 20, top: 16, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF18', borderWidth: 1, borderColor: '#FFFFFF40' },
    checklist: { borderRadius: 22, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, overflow: 'hidden', marginTop: 20, marginBottom: 16 },
    checkRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 68, padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border },
    checkRowCorrect: { backgroundColor: '#123D3B' },
    checkBox: { width: 27, height: 27, borderRadius: 8, borderWidth: 2, borderColor: colors.mutedForeground, alignItems: 'center', justifyContent: 'center' },
    checkBoxCorrect: { backgroundColor: BRAND.mint, borderColor: BRAND.mint },
    checkWord: { flex: 1, fontFamily: 'Inter_700Bold', fontSize: 16, lineHeight: 23, color: colors.foreground },
    checkStatus: { fontFamily: 'Inter_600SemiBold', fontSize: 12, color: colors.mutedForeground, paddingVertical: 5, paddingHorizontal: 8, borderRadius: 8, backgroundColor: colors.secondary },
    checkStatusCorrect: { color: BRAND.navy, backgroundColor: BRAND.mint },
    reviewSummary: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 12, marginTop: 24, padding: 22, borderRadius: 24, backgroundColor: BRAND.mint },
    reviewSummaryText: { flexShrink: 1, fontFamily: 'Inter_700Bold', fontSize: 16, color: BRAND.navy },
    reviewSummaryNote: { fontFamily: 'Inter_500Medium', fontSize: 13, color: BRAND.navy },
    reviewWarning: { marginTop: 10, textAlign: 'center', fontFamily: 'Inter_500Medium', fontSize: 12, lineHeight: 17, color: BRAND.white },
    reviewWarningStrong: { fontFamily: 'Inter_900Black', color: BRAND.orange },
    reviewFooter: { width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 20, paddingVertical: 16, backgroundColor: 'transparent' },
    reviewPrimaryButton: { backgroundColor: BRAND.orange },
    languageSelectorRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginTop: 8 },
    homeControlLabel: { fontFamily: 'Inter_900Black', fontSize: 12, letterSpacing: 0.8, color: BRAND.white },
    languageOptions: { flexDirection: 'row', gap: 6 },
    languageOption: { minWidth: 42, minHeight: 34, paddingHorizontal: 9, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF18', borderWidth: 1, borderColor: '#FFFFFF35' },
    languageOptionSelected: { backgroundColor: BRAND.orange, borderColor: BRAND.orange },
    languageOptionText: { fontFamily: 'Inter_900Black', fontSize: 12, color: BRAND.white },
    languageOptionTextSelected: { color: BRAND.navy },
    languageSelectorLabel: { display: 'none' },
    languageSelectorPillGroup: { flexDirection: 'row', gap: 6, alignItems: 'center' },
    languageSelectorPill: { minWidth: 34, height: 30, paddingHorizontal: 8, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
    languageSelectorPillActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    languageSelectorText: { fontFamily: 'Inter_700Bold', fontSize: 11, color: colors.foreground },
    languageSelectorTextActive: { color: colors.primaryForeground },
    tableRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 17, borderBottomWidth: 1, borderBottomColor: colors.border },
    tableHeader: { backgroundColor: colors.secondary },
    tableLabel: { flex: 1.4, fontFamily: 'Inter_600SemiBold', fontSize: 14, color: colors.foreground },
    tableNumber: { flex: 1, textAlign: 'center', fontFamily: 'Inter_700Bold', fontSize: 20, color: colors.foreground },
    tableHeading: { fontSize: 12, color: colors.mutedForeground },
    tableTotal: { backgroundColor: colors.secondary, borderBottomWidth: 0 },
    tableTotalNumber: { color: colors.primary, fontSize: 25 },
    safe: { flex: 1, minWidth: 0, backgroundColor: 'transparent' },
    flex: { flex: 1 },
    loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    homeScroll: { flexGrow: 1, width: '100%', maxWidth: 520, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 12, paddingBottom: 24 },
    pageScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 16, paddingBottom: 22 },
    setupScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 16, paddingTop: 0, paddingBottom: 28 },
    setupTopBar: { height: 68, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    setupBackButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF12', borderWidth: 1, borderColor: '#FFFFFF24' },
    setupBackButtonPlaceholder: { width: 42, height: 42 },
    setupLogo: { width: 195, height: 76 },
    setupHeadingWrap: { alignItems: 'center', marginTop: -6, marginBottom: 0 },
    setupTitleArt: { width: '100%', height: 220, alignSelf: 'center' },
    setupTitle: { fontFamily: 'Inter_900Black', fontSize: 43, lineHeight: 45, letterSpacing: -1.4, textAlign: 'center', color: BRAND.white, textShadowColor: '#00101F', textShadowOffset: { width: 0, height: 4 }, textShadowRadius: 2 },
    setupConfettiRow: { position: 'absolute', left: 5, right: 5, bottom: 21, flexDirection: 'row', justifyContent: 'space-between' },
    setupConfetti: { width: 13, height: 37, borderRadius: 8 },
    setupTeamCards: { gap: 14 },
    setupTeamCard: { padding: 10, borderRadius: 21, borderBottomWidth: 5, borderBottomColor: '#001A2F42', shadowColor: '#001322', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.28, shadowRadius: 12, elevation: 7 },
    setupTeamMainRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    setupTeamAvatar: { width: 78, height: 78, borderRadius: 19, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', backgroundColor: '#FFFFFF68' },
    setupTeamAvatarEmoji: { fontSize: 52, lineHeight: 60 },
    setupTeamFieldColumn: { flex: 1, minWidth: 0 },
    setupTeamTitle: { marginBottom: 6, fontFamily: 'Inter_900Black', fontSize: 19, lineHeight: 23, letterSpacing: 0.7, textAlign: 'left', color: BRAND.navy },
    setupTeamInputShell: { minHeight: 50, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, borderRadius: 13, backgroundColor: BRAND.white },
    setupTeamInput: { flex: 1, minWidth: 0, paddingVertical: 8, paddingRight: 8, fontFamily: 'Inter_700Bold', fontSize: 19, color: BRAND.navy },
    setupPickerLabel: { marginTop: 9, marginBottom: 6, marginLeft: 90, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 0.8, color: '#214B5D' },
    setupTeamIconPicker: { flexDirection: 'row', justifyContent: 'space-between', gap: 7 },
    setupTeamIconOption: { flex: 1, minWidth: 0, aspectRatio: 1, maxHeight: 46, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: BRAND.white, borderWidth: 3, borderColor: 'transparent' },
    setupTeamIconText: { fontSize: 25, lineHeight: 30 },
    setupTeamIconOptionActive: { borderColor: BRAND.navy, backgroundColor: '#FFF7C5' },
    setupDeckBlock: { marginTop: 19, marginBottom: 14 },
    familyModeOption: { minHeight: 68, marginBottom: 16, paddingHorizontal: 16, borderRadius: 18, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#FFFFFF18', borderWidth: 2, borderColor: '#FFFFFF35' },
    familyModeOptionSelected: { backgroundColor: BRAND.mint, borderColor: BRAND.orange },
    familyModeCopy: { flex: 1 },
    familyModeTitle: { fontFamily: 'Inter_900Black', fontSize: 16, color: BRAND.white },
    familyModeTitleSelected: { color: BRAND.navy },
    familyModeNote: { marginTop: 3, fontFamily: 'Inter_700Bold', fontSize: 12, color: '#B4C4D1' },
    familyModeNoteSelected: { color: BRAND.navy },
    setupSectionTitle: { marginBottom: 10, fontFamily: 'Inter_900Black', fontSize: 21, lineHeight: 25, letterSpacing: 0.4, textAlign: 'center', color: BRAND.white },
    setupCardCountList: { flexDirection: 'row', gap: 12 },
    setupCardCountOption: { flex: 1, minWidth: 0, minHeight: 94, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: BRAND.white, borderWidth: 4, borderColor: BRAND.white, borderBottomColor: '#CDD6DA' },
    setupCardCountOptionSelected: { backgroundColor: BRAND.orange, borderColor: BRAND.orange, borderBottomColor: '#B85E16' },
    setupCardCountTitle: { fontFamily: 'Inter_900Black', fontSize: 36, lineHeight: 40, color: BRAND.navy },
    setupCardCountTitleSelected: { color: BRAND.white },
    setupCardCountNote: { marginTop: 4, fontFamily: 'Inter_700Bold', fontSize: 12, textAlign: 'center', textTransform: 'uppercase', color: '#708B9C' },
    setupCardCountNoteSelected: { color: BRAND.white },
    setupCreateButton: { minHeight: 62, borderRadius: 31, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: BRAND.orange, borderBottomWidth: 5, borderBottomColor: '#B85E16' },
    setupCreateButtonText: { fontFamily: 'Inter_900Black', fontSize: 20, letterSpacing: 0.5, textAlign: 'center', textTransform: 'uppercase', color: BRAND.navy },
    heroOverline: { marginTop: 26, textAlign: 'center', fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 2, color: colors.mutedForeground },
    statsRow: { flexDirection: 'row', gap: 8, marginBottom: 18, paddingVertical: 5 },
    stat: { flex: 1, alignItems: 'center', paddingVertical: 8, gap: 3 },
    statIcon: { width: 30, height: 30 },
    statValue: { fontFamily: 'Inter_900Black', fontSize: 15, textAlign: 'center', color: colors.foreground },
    statLabel: { fontFamily: 'Inter_400Regular', fontSize: 10, color: colors.mutedForeground, textAlign: 'center' },
    primaryButton: { minHeight: 58, borderRadius: 999, paddingHorizontal: 20, paddingVertical: 14, flexDirection: 'row', gap: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: BRAND.orange, borderBottomWidth: 4, borderBottomColor: '#00000025' },
    primaryButtonText: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 16, textAlign: 'center', textTransform: 'uppercase', color: colors.primaryForeground },
    ctaArrow: { position: 'absolute', right: 20 },
    secondaryButton: { minHeight: 64, borderRadius: 22, marginTop: 12, padding: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: colors.border },
    secondaryButtonText: { fontFamily: 'Inter_600SemiBold', fontSize: 15, color: colors.foreground },
    secondaryButtonNote: { marginTop: 4, fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.mutedForeground },
    footnote: { marginTop: 18, textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, color: colors.mutedForeground },
    pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
    screenHeader: { height: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    screenHeaderTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 15, color: colors.foreground },
    screenHeaderTitleOnRound: { color: BRAND.navy },
    iconButton: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card },
    iconButtonOnRound: { backgroundColor: BRAND.white },
    iconButtonPlaceholder: { width: 38, height: 38 },
    pageEyebrow: { marginTop: 22, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.5, color: roundColor },
    pageTitle: { marginTop: 10, fontFamily: 'Inter_900Black', fontSize: 34, lineHeight: 39, letterSpacing: -1.2, color: colors.foreground },
    pageSubtitle: { marginTop: 11, fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 24, color: colors.mutedForeground },
    formBlock: { marginTop: 24 },
    fieldLabel: { marginBottom: 10, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.1, color: colors.mutedForeground },
    teamInputRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 7 },
    teamInput: { flex: 1, minWidth: 0, fontFamily: 'Inter_700Bold', fontSize: 14, color: BRAND.navy, paddingVertical: 9, paddingHorizontal: 7, borderRadius: 8, backgroundColor: BRAND.white },
    teamIconPicker: { flexDirection: 'row', gap: 4, marginTop: 10 },
    teamIconOption: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.secondary, borderWidth: 2, borderColor: colors.secondary },
    teamIconOptionActive: { backgroundColor: colors.background, borderColor: colors.primary },
    teamIconOptionText: { fontSize: 21 },
    placeholder: { color: colors.mutedForeground },
    cardCountList: { flexDirection: 'row', gap: 10 },
    cardCountOption: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 13, paddingHorizontal: 5, borderRadius: 13, backgroundColor: colors.card, borderWidth: 2, borderColor: colors.border },
    cardCountOptionSelected: { borderColor: BRAND.orange, backgroundColor: BRAND.orange },
    cardCountTitle: { textAlign: 'center', fontFamily: 'Inter_900Black', fontSize: 28, color: colors.foreground },
    cardCountTitleSelected: { color: BRAND.navy },
    cardCountNote: { marginTop: 5, textAlign: 'center', fontFamily: 'Inter_500Medium', fontSize: 11, color: colors.mutedForeground },
    infoBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginTop: 22, marginBottom: 22, padding: 17, borderRadius: 19, backgroundColor: colors.secondary, borderWidth: 1, borderColor: colors.border },
    infoText: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, color: colors.secondaryForeground },
    instructionCard: { marginTop: 8, padding: 20, borderRadius: 18, backgroundColor: BRAND.white },
    instructionTitle: { fontFamily: 'Inter_900Black', fontSize: 23, color: BRAND.navy, textAlign: 'center' },
    instructionBody: { marginTop: 10, textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, color: '#354D60' },
    instructionButton: { marginTop: 20, backgroundColor: BRAND.navy },
    scoreStrip: { flexDirection: 'row', alignItems: 'center', marginTop: 20, marginBottom: 24, padding: 18, borderRadius: 24, backgroundColor: colors.card },
    scoreTeam: { flex: 1 },
    scoreTeamRight: { alignItems: 'flex-end' },
    scoreTeamNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    scoreTeamNameRowRight: { flexDirection: 'row', alignItems: 'center', gap: 6, justifyContent: 'flex-end' },
    scoreTeamIcon: { fontSize: 16 },
    scoreTeamName: { flexShrink: 1, fontFamily: 'Inter_600SemiBold', fontSize: 12, color: colors.mutedForeground },
    scoreNumber: { marginTop: 6, fontFamily: 'Inter_900Black', fontSize: 32, color: colors.foreground },
    scoreDivider: { marginHorizontal: 16, fontFamily: 'Inter_700Bold', fontSize: 20, color: colors.mutedForeground },
    gameScreen: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 16, paddingBottom: 14 },
    playHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingTop: 14 },
    playHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 9 },
    playRound: { fontFamily: 'Inter_700Bold', fontSize: 12, lineHeight: 16, letterSpacing: 0.2, color: roundColor },
    activeTeamNameRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 5 },
    activeTeamIcon: { fontSize: 22 },
    activeTeam: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 21, color: colors.foreground },
    timer: { width: 70, height: 70, borderRadius: 35, alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: roundColor, backgroundColor: colors.background },
    timerDanger: { backgroundColor: BRAND.orange, borderColor: BRAND.white },
    timerNumber: { fontFamily: 'Inter_900Black', fontSize: 29, lineHeight: 32, color: colors.foreground },
    timerLabel: { fontFamily: 'Inter_700Bold', fontSize: 10, color: colors.foreground },
    progressTrack: { height: 7, marginTop: 18, overflow: 'hidden', borderRadius: 4, backgroundColor: colors.secondary },
    progressFill: { height: 7, borderRadius: 4, backgroundColor: roundColor },
    playCenter: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 20 },
    cardOverline: { marginBottom: 12, fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.2, color: colors.mutedForeground },
    wordCard: { position: 'relative', width: '100%', minHeight: 220, alignItems: 'center', justifyContent: 'center', padding: 18, borderRadius: 18, backgroundColor: BRAND.white, borderBottomWidth: 7, borderBottomColor: roundColor },
    cardTopRow: { position: 'absolute', top: 18, left: 18, right: 18, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center', gap: 8 },
    cardCategory: { fontFamily: 'Inter_900Black', fontSize: 16, lineHeight: 20, textAlign: 'center', textTransform: 'uppercase', color: '#40586B' },
    cardDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.border },
    wordText: { width: '100%', flexShrink: 1, textAlign: 'center', fontFamily: 'Inter_900Black', fontSize: 35, lineHeight: 42, letterSpacing: -1.3, color: BRAND.navy },
    cardSubcategory: { fontFamily: 'Inter_700Bold', fontSize: 16, lineHeight: 20, textAlign: 'center', textTransform: 'uppercase', color: '#40586B' },
    remainingText: { marginTop: 14, fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.mutedForeground },
    remainingRow: { flexDirection: 'row', alignItems: 'center', gap: 9 },
    remainingCount: { fontFamily: 'Inter_900Black', color: BRAND.white },
    playActions: { flexDirection: 'row', gap: 12 },
    passButton: { flex: 1, minHeight: 62, padding: 10, borderRadius: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: BRAND.orange, borderBottomWidth: 4, borderBottomColor: '#00000025' },
    passButtonText: { flexShrink: 1, fontFamily: 'Inter_700Bold', fontSize: 14, textAlign: 'center', textTransform: 'uppercase', color: BRAND.white },
    correctButton: { flex: 1.5, minHeight: 62, padding: 10, borderRadius: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: BRAND.mint, borderBottomWidth: 4, borderBottomColor: '#00000025' },
    correctButtonText: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 15, textAlign: 'center', textTransform: 'uppercase', color: BRAND.white },
    scoreBoard: { flexDirection: 'row', gap: 12, marginTop: 26, marginBottom: 8 },
    scoreBoardRow: { flex: 1, minWidth: 0, alignItems: 'center', padding: 18, borderRadius: 24, backgroundColor: colors.card, gap: 8 },
    scoreBoardRowLast: { borderBottomWidth: 0 },
    teamScoreBadge: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center' },
    teamScoreBadgeWarm: { backgroundColor: colors.primary },
    teamScoreBadgeGold: { backgroundColor: colors.accent },
    teamScoreInitial: { fontFamily: 'Inter_700Bold', fontSize: 18, color: colors.primaryForeground },
    scoreBoardName: { textAlign: 'center', fontFamily: 'Inter_700Bold', fontSize: 14, color: colors.foreground },
    scoreBoardPoints: { fontFamily: 'Inter_900Black', fontSize: 46, color: colors.foreground },
    pointsLabel: { fontFamily: 'Inter_400Regular', fontSize: 12, color: colors.mutedForeground },
    finalHero: { alignItems: 'center' },
    finalTitle: { marginTop: 13, fontFamily: 'Inter_900Black', fontSize: 36, lineHeight: 42, letterSpacing: -1.2, textAlign: 'center', color: BRAND.orange },
    finalScroll: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 16, paddingTop: 8, paddingBottom: 22 },
    finalCelebrationArt: { width: '100%', height: 360, alignSelf: 'center' },
    screenBrandLogo: { width: 180, height: 74, alignSelf: 'center', marginTop: 2, marginBottom: 2 },
    finalResultPanel: { marginTop: -9, padding: 16, borderRadius: 22, backgroundColor: '#FFFFFF12', borderWidth: 1, borderColor: '#FFFFFF20' },
    finalResultTitle: { fontFamily: 'Inter_900Black', fontSize: 25, lineHeight: 30, textAlign: 'center', color: BRAND.orange },
    finalResultSubtitle: { marginTop: 5, fontFamily: 'Inter_500Medium', fontSize: 14, lineHeight: 19, textAlign: 'center', color: BRAND.white },
    finalButton: { minHeight: 70, marginTop: 18, borderRadius: 35, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: BRAND.orange, borderBottomWidth: 5, borderBottomColor: '#B85E16' },
    finalButtonText: { flexShrink: 1, fontFamily: 'Inter_900Black', fontSize: 20, textAlign: 'center', textTransform: 'uppercase', color: BRAND.navy },
  });
}
